---
apiVersion: v1
kind: Service
metadata:
  name: ocp-demo-kube
  labels:
    app: ocp-demo-kube
spec:
  type: NodePort
  selector:
    app: ocp-demo-kube
  ports:
    - protocol: TCP
      port: 8080
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ocp-demo-kube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ocp-demo-kube
    spec:
      containers:
        - name: ocp-demo-kube
          image: luyaozhao2018/ocp-demo-s1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8010
            initialDelaySeconds: 30
            timeoutSeconds: 1