---
apiVersion: v1
kind: Service
metadata:
  name: ocp-demo-kube
  labels:
    run: ocp-demo-kube
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    run: ocp-demo-kube

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp-demo-kube
  labels:
    run: ocp-demo-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      run: ocp-demo-kube
  template:
    metadata:
      labels:
        run: ocp-demo-kube
    spec:
      containers:
        - name: ocp-demo
          image: luyaozhao2018/ocp-demo-s1
          ports:
            - containerPort: 8080
            - containerPort: 443